### ISSUE TITLE
testflo call broken?

### ISSUE THREAD

**Issue by relf** [OpenMDAO/testflo#21]
Hello. We used to call testflo without argument but it seems that the last PR #19 has broken this.
<pre>
(base) D:\rlafage\workspace\smt>testflo
Traceback (most recent call last):
  File "D:\rlafage\Miniconda3\Scripts\testflo-script.py", line 11, in <module>
    load_entry_point('testflo', 'console_scripts', 'testflo')()
  File "d:\rlafage\workspace\testflo\testflo\main.py", line 196, in main
    retval = run_pipeline(tests, pipeline)
  File "d:\rlafage\workspace\testflo\testflo\main.py", line 76, in run_pipeline
    for result in iters[-1]:
  File "d:\rlafage\workspace\testflo\testflo\summary.py", line 30, in get_iter
    for test in input_iter:
  File "d:\rlafage\workspace\testflo\testflo\printer.py", line 31, in get_iter
    for result in input_iter:
  File "d:\rlafage\workspace\testflo\testflo\summary.py", line 30, in get_iter
    for test in input_iter:
  File "d:\rlafage\workspace\testflo\testflo\printer.py", line 32, in get_iter
    self._print_result(result)
  File "d:\rlafage\workspace\testflo\testflo\printer.py", line 68, in _print_result
    stream.write(_result_map[(result.status, result.expected_fail)])
KeyError: (None, False)
</pre>

while running <code>testflo -n 1</code> works around the problem.

**Comment by swryan** [comment]
I'm having trouble replicating your issue.. can you try uninstalling and reinstalling testflo to make sure you have a clean install of the latest? 

I did just push a bug fix (bumping the version to 1.3.3) that might fix your issue, but I couldn't replicate your exact error with 1.3.2 before the fix.

Let me know and sorry for any inconvenience.

**Comment by relf** [comment]
Thank you for your answer. I still have the same issue with 1.3.3. As you can see below it worked with 1.3.1. With 1.3.3, the program blocks  (line <code>KeyError: (None, False)</code>), I have to press Ctrl-C. I have now the same behaviour with 1.3.2, when I send my first message, tesflo just terminated after <code>KeyError: (None, False)</code>... Maybe something wrong related to my Python 3 Windows 7 environment and multiprocessing? In any case it works when I add <code>-n 1</code> option, so as far as I am concerned, the issue can be closed.

<pre>
(base) D:\rlafage\workspace\smt>pip install testflo==1.3.1
Collecting testflo==1.3.1
Requirement already satisfied: coverage in d:\rlafage\miniconda3\lib\site-packages (from testflo==1.3.1) (4.5.1)
Requirement already satisfied: six in d:\rlafage\miniconda3\lib\site-packages (from testflo==1.3.1) (1.11.0)
Installing collected packages: testflo
  Found existing installation: testflo 1.3.3
    Uninstalling testflo-1.3.3:
      Successfully uninstalled testflo-1.3.3
Successfully installed testflo-1.3.1

(base) D:\rlafage\workspace\smt>testflo
d:\rlafage\miniconda3\lib\site-packages\sklearn\externals\joblib\externals\cloudpickle\cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
d:\rlafage\miniconda3\lib\site-packages\sklearn\externals\joblib\externals\cloudpickle\cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
d:\rlafage\miniconda3\lib\site-packages\sklearn\externals\joblib\externals\cloudpickle\cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
d:\rlafage\miniconda3\lib\site-packages\sklearn\externals\joblib\externals\cloudpickle\cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
d:\rlafage\miniconda3\lib\site-packages\sklearn\externals\joblib\externals\cloudpickle\cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
..............................................................................................................................................

OK

Passed:  142
Failed:  0
Skipped: 0


Ran 142 tests using 4 processes
Wall clock time:   00:01:17.44

(base) D:\rlafage\workspace\smt>pip install testflo==1.3.3
Collecting testflo==1.3.3
Requirement already satisfied: six in d:\rlafage\miniconda3\lib\site-packages (from testflo==1.3.3) (1.11.0)
Requirement already satisfied: coverage in d:\rlafage\miniconda3\lib\site-packages (from testflo==1.3.3) (4.5.1)
Installing collected packages: testflo
  Found existing installation: testflo 1.3.1
    Uninstalling testflo-1.3.1:
      Successfully uninstalled testflo-1.3.1
Successfully installed testflo-1.3.3

(base) D:\rlafage\workspace\smt>testflo
d:\rlafage\miniconda3\lib\site-packages\sklearn\externals\joblib\externals\cloudpickle\cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
d:\rlafage\miniconda3\lib\site-packages\sklearn\externals\joblib\externals\cloudpickle\cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
d:\rlafage\miniconda3\lib\site-packages\sklearn\externals\joblib\externals\cloudpickle\cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
d:\rlafage\miniconda3\lib\site-packages\sklearn\externals\joblib\externals\cloudpickle\cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
d:\rlafage\miniconda3\lib\site-packages\sklearn\externals\joblib\externals\cloudpickle\cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "d:\rlafage\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\rlafage\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\rlafage\Miniconda3\Scripts\testflo.exe\__main__.py", line 9, in <module>
  File "d:\rlafage\miniconda3\lib\site-packages\testflo\main.py", line 196, in main
    retval = run_pipeline(tests, pipeline)
  File "d:\rlafage\miniconda3\lib\site-packages\testflo\main.py", line 76, in run_pipeline
    for result in iters[-1]:
  File "d:\rlafage\miniconda3\lib\site-packages\testflo\summary.py", line 30, in get_iter
    for test in input_iter:
  File "d:\rlafage\miniconda3\lib\site-packages\testflo\printer.py", line 31, in get_iter
    for result in input_iter:
  File "d:\rlafage\miniconda3\lib\site-packages\testflo\summary.py", line 30, in get_iter
    for test in input_iter:
  File "d:\rlafage\miniconda3\lib\site-packages\testflo\printer.py", line 32, in get_iter
    self._print_result(result)
  File "d:\rlafage\miniconda3\lib\site-packages\testflo\printer.py", line 68, in _print_result
    stream.write(_result_map[(result.status, result.expected_fail)])
KeyError: (None, False)
Process Process-4:
Process Process-5:
Traceback (most recent call last):
Process Process-3:
Process Process-2:
  File "d:\rlafage\miniconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
Traceback (most recent call last):
Traceback (most recent call last):
  File "d:\rlafage\miniconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "d:\rlafage\miniconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "d:\rlafage\miniconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "d:\rlafage\miniconda3\lib\site-packages\testflo\runner.py", line 24, in worker
    for tests in iter(test_queue.get, 'STOP'):
  File "d:\rlafage\miniconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "d:\rlafage\miniconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "d:\rlafage\miniconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "d:\rlafage\miniconda3\lib\multiprocessing\queues.py", line 93, in get
    with self._rlock:
  File "d:\rlafage\miniconda3\lib\site-packages\testflo\runner.py", line 24, in worker
    for tests in iter(test_queue.get, 'STOP'):
  File "d:\rlafage\miniconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "d:\rlafage\miniconda3\lib\site-packages\testflo\runner.py", line 24, in worker
    for tests in iter(test_queue.get, 'STOP'):
  File "d:\rlafage\miniconda3\lib\multiprocessing\synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "d:\rlafage\miniconda3\lib\multiprocessing\queues.py", line 93, in get
    with self._rlock:
  File "d:\rlafage\miniconda3\lib\site-packages\testflo\runner.py", line 24, in worker
    for tests in iter(test_queue.get, 'STOP'):
  File "d:\rlafage\miniconda3\lib\multiprocessing\queues.py", line 93, in get
    with self._rlock:
KeyboardInterrupt
  File "d:\rlafage\miniconda3\lib\multiprocessing\synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "d:\rlafage\miniconda3\lib\multiprocessing\queues.py", line 94, in get
    res = self._recv_bytes()
  File "d:\rlafage\miniconda3\lib\multiprocessing\synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
  File "d:\rlafage\miniconda3\lib\multiprocessing\connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
KeyboardInterrupt
  File "d:\rlafage\miniconda3\lib\multiprocessing\connection.py", line 306, in _recv_bytes
    [ov.event], False, INFINITE)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "d:\rlafage\miniconda3\lib\multiprocessing\util.py", line 319, in _exit_function
    p.join()
  File "d:\rlafage\miniconda3\lib\multiprocessing\process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "d:\rlafage\miniconda3\lib\multiprocessing\popen_spawn_win32.py", line 80, in wait
    res = _winapi.WaitForSingleObject(int(self._handle), msecs)
KeyboardInterrupt

(base) D:\rlafage\workspace\smt>testflo -n 1
d:\rlafage\miniconda3\lib\site-packages\sklearn\externals\joblib\externals\cloudpickle\cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
..............................................................................................................................................

OK

Passed:  142
Failed:  0
Skipped: 0


Ran 142 tests using 1 processes
Wall clock time:   00:02:4.77
</pre>

**Comment by swryan** [comment]
Will continue investigating... suggest you just stick with 1.3.1 in the meantime, since you don't need the new ISOLATED feature.  Thanks for the feedback.

**Comment by swryan** [comment]
I believe I have identified the bug... if you have a moment, please try updating from github master and let me know.  Thanks!
