### ISSUE TITLE
Run on sub-sub-modules does not work

### ISSUE THREAD

**Issue by relf** [OpenMDAO/testflo#24]
With testflo 1.3.4 and the example from the README, I get:
<pre>
(base) D:\rlafage\workspace\OpenMDAO\openmdao>testflo openmdao.core.test.test_problem
openmdao.core.test.test_problem ... FAIL (00:00:0.00, 0 MB)
Traceback (most recent call last):
  File "d:\rlafage\miniconda3\lib\site-packages\testflo\discover.py", line 129, in _module_iter
    fname, mod = get_module(filename)
  File "d:\rlafage\miniconda3\lib\site-packages\testflo\util.py", line 309, in get_module
    raise ImportError("can't import %s" % modpath)
ImportError: can't import openmdao.core.test.test_problem

The following tests failed:
openmdao.core.test.test_problem:openmdao.core.test.test_problem

Passed:  0
Failed:  1
Skipped: 0

Ran 1 test using 4 processes
Wall clock time:   00:00:0.52

(base) D:\rlafage\workspace\OpenMDAO\openmdao>testflo openmdao.core.test
openmdao.core.test ... FAIL (00:00:0.00, 0 MB)
Traceback (most recent call last):
  File "d:\rlafage\miniconda3\lib\site-packages\testflo\discover.py", line 129, in _module_iter
    fname, mod = get_module(filename)
  File "d:\rlafage\miniconda3\lib\site-packages\testflo\util.py", line 309, in get_module
    raise ImportError("can't import %s" % modpath)
ImportError: can't import openmdao.core.test

The following tests failed:
openmdao.core.test:openmdao.core.test

Passed:  0
Failed:  1
Skipped: 0

Ran 1 test using 4 processes
Wall clock time:   00:00:0.50

</pre>

while running on sub-module is ok

<pre>

(base) D:\rlafage\workspace\OpenMDAO\openmdao>testflo openmdao.core
.....................S.....S.S..SS.S.S.S.........................................................................S....SSSSSSSSSSS......SS.........SS.SSSSSS.......S...............S.SSSSS.......S..............................SSSS....SSSSSSSSS
SSS.SS.SSSSSS................................................................................................................................................................................................................S.SSSSSSS.SSSSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.................SSSSSSSSS..................................................S.SSSSSSSSSSS.XXXXX.X.S.S.....S................................

OK

Passed:  516
Failed:  0
Skipped: 139

Ran 655 tests using 4 processes
Wall clock time:   00:00:7.57

</pre>

**Comment by relf** [comment]
ok, my bad. It is openmdao.core.tests not test.
