### ISSUE TITLE
Error handling OpenMDAO's `USE_PROC_FILES` feature

### ISSUE THREAD

**Issue by swryan** [OpenMDAO/testflo#68]
### Issue Type

- [x] Bug
- [ ] Enhancement  

### Description

testflo fails when `import openmdao.api` is called within a test and the `USE_PROC_FILES` environment variable is set

### Example

```python
[11:59:56](OM) ~$ cat test_import.py
import unittest

import numpy as np


class TestBug(unittest.TestCase):

    N_PROCS=2

    def test_import(self):
        import openmdao.api as om


if __name__ == '__main__':
    unittest.main()
[11:59:59](OM) ~$ export USE_PROC_FILES=1
[12:00:07](OM)~$ testflo test_import.py
(mpi) test_import.py:TestBug.test_import ... FAIL (00:00:0.39, 205 MB)
Traceback (most recent call last):
  File "/home/swryan/miniconda3/envs/OM/lib/python3.9/site-packages/testflo/test.py", line 418, in _try_call
    func()
  File "/home/swryan/test_import.py", line 11, in test_import
    import openmdao.api as om
  File "/home/swryan/dev/OpenMDAO/openmdao/api.py", line 4, in <module>
    from openmdao.core.problem import Problem
  File "/home/swryan/dev/OpenMDAO/openmdao/core/problem.py", line 17, in <module>
    from openmdao.core.component import Component
  File "/home/swryan/dev/OpenMDAO/openmdao/core/component.py", line 13, in <module>
    from openmdao.core.system import System, _supported_methods, _DEFAULT_COLORING_META, \
  File "/home/swryan/dev/OpenMDAO/openmdao/core/system.py", line 25, in <module>
    from openmdao.utils.mpi import MPI, multi_proc_exception_check
  File "/home/swryan/dev/OpenMDAO/openmdao/utils/mpi.py", line 374, in <module>
    use_proc_files()
  File "/home/swryan/dev/OpenMDAO/openmdao/utils/mpi.py", line 57, in use_proc_files
    _redirect_streams(ofile.fileno())
  File "/home/swryan/dev/OpenMDAO/openmdao/utils/mpi.py", line 29, in _redirect_streams
    original_stdout_fd = sys.stdout.fileno()
AttributeError: 'DevNull' object has no attribute 'fileno'



The following tests failed:
test_import.py:TestBug.test_import


Passed:  0
Failed:  1
Skipped: 0


Ran 1 test using 12 processes
Wall clock time:   00:00:0.77

[12:00:22](OM) ~$ unset USE_PROC_FILES
[12:00:29](OM) ~$ testflo test_import.py
.

OK

Passed:  1
Failed:  0
Skipped: 0


Ran 1 test using 12 processes
Wall clock time:   00:00:1.45

[12:00:32](OM) swryan@Chimaera:~$
```

### Environment

Operating System: Ubuntu 20.04, CentOS 7.9

Python environment: Python 3.7 and Python 3.9

Packages: OpenMDAO 3.18.1-dev, testflo 1.4.8

**Comment by swryan** [comment]
This no longer appears to be an issue:
```
$ testflo -vs ~/testbug.py

(mpi) /home/swryan/testbug.py:TestBug.test_import ... OK (00:00:3.75, 672 MB)


OK

Passed:  1
Failed:  0
Skipped: 0


Ran 1 test using 12 processes
Wall clock time:   00:00:4.95

$ env | grep PROC
USE_PROC_FILES=1
[$ unset USE_PROC_FILES
$ !te
testflo -vs ~/testbug.py

(mpi) /home/swryan/testbug.py:TestBug.test_import ... OK (00:00:1.73, 668 MB)


OK

Passed:  1
Failed:  0
Skipped: 0


Ran 1 test using 12 processes
Wall clock time:   00:00:2.73
```
